# Run-or-Raise shortcuts
# Format: shortcut[:mode[:mode]],command,[wm_class],[title]

<Super>t:minimize-when-unfocused:switch-back-when-focused,ghostty,,
<Super>b:minimize-when-unfocused:switch-back-when-focused,firefox,firefox,
<Super>h:minimize-when-unfocused:switch-back-when-focused,helium,,
<Super>e:minimize-when-unfocused:switch-back-when-focused,zed,,
<Super>g,wofi-emoji
<Super>Escape:minimize-when-unfocused:switch-back-when-focused,org.gnome.Settings.desktop,org.gnome.Settings,
<Super>space:minimize-when-unfocused:switch-back-when-focused,org.gnome.Nautilus.desktop,org.gnome.Nautilus,
<Super>c:minimize-when-unfocused:switch-back-when-focused,code,Code,
