# Run-or-Raise shortcuts
# Format: shortcut[:mode[:mode]],command,[wm_class],[title]

<Control><Alt><Shift>t:minimize-when-unfocused:switch-back-when-focused,ghostty,,
<Control><Alt><Shift>b:minimize-when-unfocused:switch-back-when-focused,firefox,firefox,
<Control><Alt><Shift>h:minimize-when-unfocused:switch-back-when-focused,helium-browser,helium,
<Control><Alt><Shift>e:minimize-when-unfocused:switch-back-when-focused,zed,,
<Control><Alt><Shift>g,wofi-emoji
<Control><Alt><Shift>F12:minimize-when-unfocused:switch-back-when-focused,org.gnome.Settings.desktop,org.gnome.Settings,
<Control><Alt><Shift>space:minimize-when-unfocused:switch-back-when-focused,org.gnome.Nautilus.desktop,org.gnome.Nautilus,
<Control><Alt><Shift>c:minimize-when-unfocused:switch-back-when-focused,code,Code,
